version : '3.8'
services:
  stationui:
    image: aelmendorf234/station_ui:latest
    container_name: station_ui
    pull_policy: always
    ports:
      - "80:8080"
    restart: unless-stopped
    environment:
      - StationServiceUrl=http://station-service
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://+:80
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
    depends_on:
      - station_service
      - mongodb
  station-service:
    image: aelmendorf234/station-service:latest
    container_name: station_service
    pull_policy: always
    privileged: true
    restart: unless-stopped
    user: "root"
    entrypoint: ["ash", "-c", "/scripts/entry-point.sh"]
    environment:
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_HTTP_PORTS=80
        - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
    ports:
      - "80:80"
    volumes:
      - /home/setiburnin/StationSoft/StationService/app:/scripts
      - /dev:/dev
    depends_on:
      - mongodb
  mongodb:
    image: mongodb-raspberrypi4-unofficial-r7.0.4
    container_name: mongodb
    pull_policy: never
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /home/setiburnin/StationSoft/mongo/db:/data/db


    
