version : '3.8'
services:
  station.ui:
    image: aelmendorf234/station-ui:latest
    container_name: station.ui
    pull_policy: always
    ports:
      - "80:8080"
      - "5581:5581"
    restart: unless-stopped
    environment:
      - StationServiceUrl=http://station.service
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
    depends_on:
      - station_service
      - mongodb
  station.service:
    image: aelmendorf234/station-service:latest
    container_name: station.service
    pull_policy: always
    privileged: true
    restart: unless-stopped
    user: "root"
    entrypoint: ["ash", "-c", "/scripts/entry-point.sh"]
    environment:
        - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
    ports:
      - "5000:5000"
      - "5580:5580"
    volumes:
      - /home/setiburnin/StationSoft/StationService/app:/scripts
      - /dev:/dev
    depends_on:
      - mongodb
  mongodb:
    image: mongodb-raspberrypi4-unofficial-r7.0.4
    container_name: mongodb
    pull_policy: never
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /home/setiburnin/StationSoft/mongo/db:/data/db


    
