services:
  station-ui:
    image: aelmendorf234/station-ui:latest
    container_name: station-ui
    pull_policy: always
    expose:
      - 8080
    ports:
      - "80:8080"
    restart: unless-stopped
    environment:
      - StationId=S08
      - StationHub=http://station-service:8080/hubs/station
      - HostHub=http://10.5.0.1:4000/hubs/host
      - MONGO_CONNECTION=mongodb://172.20.3.41:27017
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - station-service
    links:
      - "station-service"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      station_net:
        ipv4_address: 10.5.0.10
  station-service:
    privileged: true
    image: aelmendorf234/station-service:latest
    container_name: station-service
    pull_policy: always
    restart: unless-stopped
    user: "root"
    entrypoint: ["ash", "-c", "/scripts/entry-point.sh"]
    environment:
      - StationId=S08
      - MONGO_CONNECTION=mongodb://172.20.3.41:27017
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    expose:
      - 8080
    ports:
      - "5000:8080"
    volumes:
      - /home/setitech/Documents/StationSoft/StationService/app:/scripts
      - /home/setitech/Documents/StationSoft/StationService/app/updates:/updates
      - /home/setitech/Documents/StationLogs:/test-logs
      - /dev:/dev
    networks:
      station_net:
        ipv4_address: 10.5.0.11
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --http-api-update
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=station-soft-token
    ports:
      - 8080:8080
    networks:
      station_net:
        ipv4_address: 10.5.0.12
networks:
  station_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1