
version : '3.8'
services:
  station.ui:
    image: aelmendorf234/station-ui:latest
    container_name: station.ui
    pull_policy: always
    expose:
      - 80
      - 5581
    ports:
      - "80:8080"
      - "4000:5581"
    restart: unless-stopped
    environment:
      - StationHub=http://station-service:8080/hubs/station
      - MsgEndpoint=10.5.0.11
      # - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
    depends_on:
      - station-service
      # - mongodb
    links:
      - "station-service"
      # - "mongodb"
    networks:
      station_net:
        ipv4_address: 10.5.0.10

  station-service:
    image: aelmendorf234/station-service:latest
    container_name: station-service
    pull_policy: always
    privileged: true
    restart: unless-stopped
    user: "root"
    entrypoint: ["ash", "-c", "/scripts/entry-point.sh"]
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
    expose:
      - 8080
      - 5580
    ports:
      - "5000:8080"
      - "5580:5580"
    volumes:
      - /home/setiburnin/StationSoft/StationService/app:/scripts
      - /dev:/dev
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    #links:
    #  - "mongodb"
    #depends_on:
      #- mongodb
    networks:
      station_net:
        ipv4_address: 10.5.0.11

  # mongodb:
  #   image: mongodb-raspberrypi4-unofficial-r7.0.4
  #   container_name: mongodb
  #   pull_policy: never
  #   restart: unless-stopped
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=false"
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - /home/setiburnin/StationSoft/mongo/db:/data/db
  #   networks:
  #     station_net:
  #       ipv4_address: 10.5.0.12

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10
    networks:
      station_net:
        ipv4_address: 10.5.0.13

networks:
  station_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1