name: Station Service Workflow
on:
  push:
    branches: [ "master" ]
jobs:
  deploy-s01:
    runs-on: [burn-in]
    steps:
      - run: |
          cd /home/setitech/Documents/StationSoft/StationService/app/updates/
          touch "test_update.txt"
