name: Station Service Workflow
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ARM64
    steps:
      - run: |
          cd /home/setitech/Documents/StationSoft/StationService/app/updates/
          touch "test_update.txt"
