name: Deploy Test
on:
  push:
    branches: [ "master" ]
jobs:
  deploy-s01:
    runs-on: [burn-in,S01]
    steps:
      - run: |
          cd /home/setitech/Documents/StationSoft/StationService/app/updates/
          touch "test_update.txt"
  deploy-s08:
    runs-on: [burn-in,S08]
    steps:
      - run: |
          cd /home/setitech/Documents/StationSoft/StationService/app/updates/
          touch "test_update.txt"
