name: Docker Config Deploy
on:
  workflow_dispatch:
  # push:
  #   branches: ["master"]
  #   paths:
  #   - 'BurnInControl.HostRunner/**'
jobs:
  mod-docker-S01:
    runs-on: ubuntu-latest
    env: 
      system: S01
    steps:
    - uses: actions/checkout@v4
    - name: Create Docker File
      run: |
        cp ./docker-compose.yml ./docker-compose-${{system}}.yml
    - name: Replace single file
      uses: richardrigutins/replace-in-files@v2
      with:
        files: 'docker-compose-${{system}}.yml'
        search-text: '{SYS}'
        replacement-text: '${{system}}'
    - name: Upload ${{system}} artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker_compose_${{system}}
        path: docker-compose-${{system}}.yml
  deploy-S01:
    needs: mod-docker-S01
    runs-on: [burn-in,S08]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: docker_compose_S08
    - name: Make Dir
      run: mkdir -p /home/setitech/test_mod_docker
    - name: Extract artifact
      run: cp docker-compose-S08.yml /home/setitech/test_mod_docker/docker-dompose.yml
      
