name: Docker Image CI
on:
  push:
    branches: [ "master" ]
    paths:
    - 'BurnInControl.Data/**'
    - 'BurnInControl.Infrastructure/**'
    - 'BurnInControl.Application/**'
    - 'BurnInControl.Shared/**'
    - 'BurnInControl.UI.Shared/**'
    - 'BurnInControl.UI/**'
    - '.github/workflows/station-ui-build.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BurnInControl.UI
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.Docker_Username}}
        password: ${{secrets.Docker_Password}}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./BurnInControl.StationService/Dockerfile
        push: true
        tags: ${{secrets.Docker_Username}}/station-ui:latest
