name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
    - 'BurnInControl.Data/**'
    - 'BurnInControl.Infrastructure/**'
    - 'StationService.Infrastructure/**'
    - 'BurnInControl.StationService/**'
    - '.github/workflows/station-service-build.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BurnInControl.StationService
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.Docker_Username}}
        password: ${{secrets.Docker_Password}}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./BurnInControl.StationService/Dockerfile
        push: true
        tags: ${{secrets.Docker_Username}}/station-service:latest
          
