name: Service Dev Deploy
on:
  push:
    branches: [ "master" ]
    paths:
    - 'BurnInControl.Data/**'
    - 'BurnInControl.Infrastructure/**'
    - 'StationService.Infrastructure/**'
    - 'BurnInControl.StationService/**'
    - '.github/workflows/station_service_action_dev.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Adjust NuGet Config Credentials
      run: |
        cp ./nuget.bak ./NuGet.config
        echo $(sed -e "s@\${PAT}@${{ secrets.NUGET_TOKEN }}@" NuGet.config) > NuGet.config
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.Docker_Username}}
        password: ${{secrets.Docker_Password}}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./BurnInControl.StationService/Dockerfile
        push: true
        tags: ${{secrets.Docker_Username}}/station-service:dev
  deploy:
    needs: build
    runs-on:
     group: burn-in-runners
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd /home/setitech/Documents/StationSoft/StationService/app/updates/
          touch "service_update.txt"
      
