name: Station UI Workflow
on:
  push:
    branches: [ "master" ]
    paths:
    - 'BurnInControl.Data/**'
    - 'BurnInControl.Infrastructure/**'
    - 'BurnInControl.Application/**'
    - 'BurnInControl.Shared/**'
    - 'BurnInControl.UI.Shared/**'
    - 'BurnInControl.UI/**'
    - '.github/workflows/station-ui-build.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Adjust NuGet Config Credentials
      run: |
        cp ./nuget.bak ./NuGet.config
        echo $(sed -e "s@\${PAT}@${{ secrets.NUGET_TOKEN }}@" NuGet.config) > NuGet.config
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.Docker_Username}}
        password: ${{secrets.Docker_Password}}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./BurnInControl.UI/Dockerfile
        push: true
        tags: ${{secrets.Docker_Username}}/station-ui:dev
  deploy:
    needs: build
    runs-on:
     group: burn-in-runners
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd /home/setitech/Documents/StationSoft/StationService/app/updates/
          touch "ui_update.txt"
